apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-cluster
  region: us-east-1

privateCluster:
  enabled: true
  additionalEndpointServices:
  - "autoscaling"

vpc:
  subnets:
    private:
      us-east-1b:
        id: subnet-0dac57cc82ab02ad3
      us-east-1a:
        id: subnet-0671af84ec6637571
      


nodeGroups:
- name: ng1
  instanceType: t2.micro
  desiredCapacity: 2
  # privateNetworking must be explicitly set for a fully-private cluster
  # Rather than defaulting this field to true for a fully-private cluster, we require users to explicitly set it
  # to make the behaviour explicit and avoid confusion.
  privateNetworking: true

managedNodeGroups:
- name: m1
  instanceType: t2.micro
  desiredCapacity: 2
  privateNetworking: true